# Generated by Django 4.1.7 on 2023-02-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Editors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='books',
            name='language',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='books',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='category',
            field=models.ManyToManyField(to='books.category'),
        ),
        migrations.AddField(
            model_name='books',
            name='editors',
            field=models.ManyToManyField(to='books.editors'),
        ),
    ]
