# Generated by Django 4.1.7 on 2023-02-27 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_editors_editor_rename_editors_books_editor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='editor',
        ),
        migrations.AddField(
            model_name='books',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.editor'),
        ),
    ]
