# Generated by Django 4.1.7 on 2023-02-27 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_books_editor_books_editor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name_plural': 'Books'},
        ),
    ]
