# Generated by Django 4.1.7 on 2023-03-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_readbooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readbooks',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
