# Generated by Django 4.1.7 on 2023-03-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_readbooks_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readbooks',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
