# Generated by Django 4.1.7 on 2023-03-01 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_readbooks_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readbooks',
            name='user',
        ),
    ]
