# Generated by Django 4.1.7 on 2023-03-01 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_readbooks_user_alter_books_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadBooks',
        ),
    ]
