# Generated by Django 4.1.7 on 2023-03-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_readbooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='books.category'),
        ),
    ]
