# Generated by Django 4.1.7 on 2023-03-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_alter_readbooks_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readbooks',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
