# Generated by Django 4.1.7 on 2023-03-06 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_alter_readbooks_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readbooks',
            name='author',
        ),
        migrations.RemoveField(
            model_name='readbooks',
            name='category',
        ),
        migrations.RemoveField(
            model_name='readbooks',
            name='description',
        ),
        migrations.RemoveField(
            model_name='readbooks',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='readbooks',
            name='language',
        ),
        migrations.RemoveField(
            model_name='readbooks',
            name='price',
        ),
        migrations.RemoveField(
            model_name='readbooks',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='readbooks',
            name='title',
        ),
        migrations.AddField(
            model_name='readbooks',
            name='book',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='books.books'),
            preserve_default=False,
        ),
    ]
