# Generated by Django 4.1.7 on 2023-03-06 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_alter_readbooks_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readbooks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
