# Generated by Django 4.1.7 on 2023-03-07 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0026_alter_readbooks_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readbooks',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.books'),
        ),
    ]
