# Generated by Django 4.1.7 on 2023-03-07 15:05

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0027_alter_readbooks_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='profile/default/default.png', upload_to=books.models.user_image),
        ),
    ]
